name: GitHub Actions CI
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  python-ci:
    runs-on: self-hosted
    steps:
      - run: echo "ğŸ‰ Event triggered by ${{ github.event_name }}"
      - name: Analysing the code with pylint
        run: |
          pylint *
      - name: Building docker image
        run: |
          docker build . --file Dockerfile --tag python_ci
      - run: echo "ğŸ This job's status is ${{ job.status }}."
