name: GitHub Actions CI
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  python-ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pylint
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Analysing the code with pylint
        run: |
          pylint --fail-under=5 app/*
      - name: Building docker image
        run: |
          docker build . --tag python_ci
      - run: echo "ğŸ This job's status is ${{ job.status }}."
